### ISSUE TITLE
Running nekRS on HPC systems

### ISSUE THREAD

**Issue by stgeke** [JezSw/nekRS#14]
- [ ] Explain how to use helper scripts
- [ ] Explain how to setup new helper scripts (what needs special attention)

**Comment by JezSw** [comment]
Location set as [doc/source/user_guide/running.rst:45](https://github.com/JezSw/nekRS/blob/f388117bd3e6a5baa4a5badc9e5f242c68e1ef45/doc/source/user_guide/running.rst?plain=1#L45)
