### ISSUE TITLE
Models and Source Terms

### ISSUE THREAD

**Issue by JezSw** [JezSw/nekRS#25]

**Comment by JezSw** [comment]
@hapfang to review

**Comment by hapfang** [comment]
Consider providing some more detailed guidelines regarding how to set up non-trivial Dirichlet BCs for k and tau at the inlet (where constant values are in general not recommended.)

**Comment by hapfang** [comment]
Makes sense to me Nadish. I have reviewed the the "Models and Source Terms" section, and it looks great. Perhaps just one minor comment for the momentum and scalar sources at the end, we can remind users the non-dimensional forms of these source terms can be found in the section "Solving in Dimensional vs Non-Dimensional Form". Anyways, the branch is ready to be merged.  Thanks for the efforts Nadish!

**Comment by JezSw** [comment]
@hapfang added that note in commits a49910b and 53e7687. Thanks both for the work I'll merge it in now.
